### ISSUE TITLE
Missing Youtube JS dist directory

### ISSUE THREAD

**Issue by manuelbachl** [lochmueller/html5videoplayer#31]
Hi there, good morning,
I've installed your Extension yesturday and I'm pretty happy with its functionality. But atm at version 7.2.2 it seems you've missed to compile the js files for youtube. The required "dist"-directory is missing. As a workaround I'm linking the unminified version directly from the src directory:

```
plugin.html5videoplayer.skipHtmlHeaderInformation = 1
page.includeJS.html5videoplayerYouTube = web/typo3conf/ext/html5videoplayer/Resources/Public/videojs-youtube-2.4.0/src/Youtube.js
```

**Comment by lochmueller** [comment]
Strange. This is the include:
https://github.com/lochmueller/html5videoplayer/blob/master/Classes/Controller/VideoplayerController.php#L255
and there is the file:
https://github.com/lochmueller/html5videoplayer/tree/master/Resources/Public/videojs-youtube-2.4.1/dist

... ahh.. I found. Already fixed in the current master: https://github.com/lochmueller/html5videoplayer/commit/646e637832a09125b773a86e3d04e1d064478dc1
Will be part of the next release.
